### ISSUE TITLE
The tts is not working

### ISSUE THREAD

**Issue by Kaifsarkar53** [1999AZZAR/bard-powered-telegram-bot#11]
The error when I tap on the tts button on telegram and it sends nothing.

![Screenshot_20231116_150047_Chrome](https://github.com/1999AZZAR/bard-powered-telegram-bot/assets/149664691/13fdcdcc-7253-4dea-9d5c-506e51046648)

The env file looks like this:

![Screenshot_20231116_150302_Chrome](https://github.com/1999AZZAR/bard-powered-telegram-bot/assets/149664691/8598278d-4734-4ff1-a93c-ecc27814eea5)

And the response is too slow and when I ask the bot to send a long article on google it just sends nothing please can you fix it can it is possible instead of sending the response it sends a message "..." then update the Bard response in that.

**Comment by 1999AZZAR** [comment]
Please just add a detaileds about it, where u run it or what environment you are on, just just give a title and blank detail

**Comment by Kaifsarkar53** [comment]
I have added the details can you please fix it.

**Comment by 1999AZZAR** [comment]
I just tried it again, and there doesn't seem to be anything wrong. Everything is working as intended. You can try running this text-to-speech (TTS) example: https://github.com/1999AZZAR/Telegram-Bot-Playground/tree/master/text_to_speech. If it works, then you're good to go. However, if it doesn't, I believe there might be something you're still missing.
